import urllib.request
import re
import os
import ssl

# Target URL
URL = "https://fiskal.kemenkeu.go.id/informasi-publik/kurs-pajak"
OUTPUT_FILE = r"c:\Users\LENOVO\.gemini\antigravity\scratch\duty-tax-calculator\kurs_data.js"

def fetch_kurs():
    print(f"Fetching {URL}...")
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    
    # Bypass SSL verification if needed (for local dev environments)
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

    req = urllib.request.Request(URL, headers=headers)
    try:
        with urllib.request.urlopen(req, context=ctx) as response:
            html_content = response.read().decode('utf-8')
            return html_content
    except Exception as e:
        print(f"Error fetching URL: {e}")
        return None

def parse_data(html):
    # 1. Find Date Range
    # Pattern: Tanggal Berlaku: 17 Desember 2025 - 23 Desember 2025
    date_pattern = r"Tanggal Berlaku:\s*([A-Za-z0-9\s\-]+)"
    date_match = re.search(date_pattern, html)
    date_range = date_match.group(1).strip() if date_match else "Unknown Date"
    
    # 2. Find USD Rate
    # Looking for row with "Amerika Serikat (USD)"
    # Structure roughly: <td>Amerika Serikat (USD)</td> ... <td>16.675,00</td>
    # We'll look for the text, then find the next numeric pattern in a TD
    
    # Simple strategy: Find "Amerika Serikat (USD)" index, then look ahead for the rate pattern
    usd_idx = html.find("Amerika Serikat (USD)")
    if usd_idx == -1:
        print("Could not find 'Amerika Serikat (USD)' in content.")
        return None, date_range

    # Look at the chunk after USD
    chunk = html[usd_idx:usd_idx+500] 
    # expected: ... </td> <td> ... </td> <td>16.675,00</td>
    
    # Regex for Indonesian number format: XX.XXX,XX
    rate_pattern = r">([0-9]{1,3}(?:\.[0-9]{3})*(?:,[0-9]+))<"
    # Find all matches in the chunk
    rates = re.findall(rate_pattern, chunk)
    
    if rates:
        # User said it's the 3rd column. 
        # Col 1: Name (USD) -> matched.
        # Col 2: Currency Code? Or Per unit? 
        # Usually: Name | Unit | Rate. 
        # So it might be the 1st or 2nd number found after the name.
        # Let's take the first one that looks like a valid exchange rate (> 10000)
        # But wait, it might be 1.00 USD = 16.000...
        
        raw_rate = rates[0] # Try first one
        # Clean it: 16.675,00 -> 16675.00
        clean_rate_str = raw_rate.replace('.', '').replace(',', '.')
        rate_val = float(clean_rate_str)
        
        print(f"Found Rate: {raw_rate} -> {rate_val}")
        print(f"Found Date: {date_range}")
        
        return rate_val, date_range
    
    return None, date_range

def update_file(rate, date):
    content = f"""// AUTO-GENERATED by auto_update_kurs.py
window.KURS_DATA = {{
    "rate": {rate},
    "date": "{date}",
    "source": "{URL}"
}};
"""
    try:
        with open(OUTPUT_FILE, 'w') as f:
            f.write(content)
        print(f"Successfully updated {OUTPUT_FILE}")
    except Exception as e:
        print(f"Error writing file: {e}")

if __name__ == "__main__":
    html = fetch_kurs()
    if html:
        rate, date_range = parse_data(html)
        if rate:
            update_file(rate, date_range)
        else:
            print("Failed to extract rate.")
