// AUTO-GENERATED by auto_update_kurs.py
window.KURS_DATA = {
    "rate": 16675.0,
    "date": "17 Desember 2025 - 23 Desember 2025",
    "source": "https://fiskal.kemenkeu.go.id/informasi-publik/kurs-pajak"
};
